### ISSUE TITLE
工作笔记

### ISSUE THREAD

**Issue by liSNS** [liSNS/liSNS.github.io#16]
#### （1）、通过viewport + REM的方式来兼容。
目前这种兼容方案相对比较完美，适合新项目（老项目改用REM单位成本会比较高）。淘宝M首页就是这种方案。

在devicePixelRatio = 2 时，输出viewport
```html
<meta name="viewport" content="initial-scale=0.5, maximum-scale=0.5, minimum-scale=0.5, user-scalable=no">
```
在devicePixelRatio = 3 时，输出viewport
```html
<meta name="viewport" content="initial-scale=0.3333333333333333, maximum-scale=0.3333333333333333, minimum-scale=0.3333333333333333, user-scalable=no">
```
<p>同时通过设置对应viewport的rem基准值，这种方式就可以像以前一样轻松愉快的写1px了。关于REM布局，可以参考下这篇文章<a href="http://www.ghugo.com/mobile-h5-fluid-layout-for-iphone6/" target="_blank">《移动端H5页面之iphone6的适配》</a></p>
#### （2）、用图片
```css
.border-image{
    border-image:url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAAECAYAAABP2FU6AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAB5JREFUeNpiPnH8zH/G////MzAxAAHTyRNn/wMEGABpvQm9g9TJ1QAAAABJRU5ErkJggg==") 2 0 stretch;
border-width: 0px 0px 1px;
}
```
优点：无

缺点：
也可以通过修改图片来达到圆角的效果，但是由于图片的原因，压缩过后的图片边缘变模糊了（不放大的情况下不明显），需要引用图片或者base64，边框颜色修改起来不方便。
<h2 id="ajax-跨域解决之jsonp">2.AJAX-跨域解决之JSONP</h2>
<ul>
<li>跨域的问题 <br>
<ul><li>域：域名</li>
<li>跨域请求（访问）：一个域名下的文件请求另外一个域名下的资源，就产生了跨域</li></ul></li>
<li>跨域的解决 <br>
<ul><li>Jsonp：json with padding</li></ul></li>
<li>&lt;script&gt;标签 <br>
<ul><li>src的作用：加载（包含指定的外部文件） <br>
<ul><li>可以跨域包含</li>
<li>被包含的资源可以是任何类型的文件（可以是txt、php等）</li>
<li>它只关注被包含的文件的内容是否是合法的js</li></ul></li></ul></li>
<li>原理 <br>
<ul><li>定义函数</li>
<li>包含外部文件，在被包含的文件中执行调用定义好的函数</li>
<li>参数的（数据）的实现 <br>
<ul><li>问题：包含就调用，通过动态创建&lt;script&gt;实现按需调用</li>
<li>问题：包含动态文件时可以通过一个接口实现按需生成调用函数名称</li></ul></li></ul></li>
</ul>
<p>在资源加载进来之前定义好一个函数，这个函数接收一个参数（数据），函数里面利用这么参数做一些事情。</p>
<p>然后需要的时候通过script标签加载对应远程文件资源，当远程文件资源被加载进来的时候，就会去执行我们前面定义好的函数，并且把数据当作这个函数的参数传入进去。</p>
